1주차
JNU-econovation/web-with-js pull request #6
Opened 2020-02-18 06:25 UTC by ummaeha

여러모로 아쉬움이 많이 남는 첫 PR
1. java로 로직짜는 연습만 되어있어서 코드가 자바스크립트 문법을 잘 사용하고 있지못함  
2. 하드코딩함  
3. 두 번째 테스트 케이스 오류생김 (NaN)  
4. 결국 원리를 배제하고 결과만을 위한 코딩이 되어버림ㅜㅡㅜ  

log.js를 모듈화 시켰을때의 이점을 잘 모르겠음.(사실 어떻게 모듈화 시켜야할지도 잘 모르겠음)

2020-02-18 14:38 UTC, GiPyoo requested changes
ES6의 기본적인 문법을 잘 지키려고 한 것이 보입니다. 이 외에 더 좋은 기능인 Object.keys()와 같은 메서드들을 이용한다면 코드가 더 깔끔해지고 다른 사람이 이해하기에 더 좋은 코드가 될 것 같습니다. 그리고 컨버터 함수가 하는 일과 책임이 너무 많아 이런 책임들을 잘 분산하신다면 더 좋은 코다가 될 것입니다. 리뷰 반영해주시고 다시 푸시 해주세요!

2020-02-18 14:38 UTC, GiPyoo commented on sprint-1/domain/time-converter.js
> +    } else if (
리턴이 있다면 else if를 사용하지 않아도 케이스를 넘길 것 같습니다.

2020-02-18 14:38 UTC, GiPyoo commented on sprint-1/domain/time-converter.js
> +  converter() {
컨버터 함수가 많은 일을 한 것 같아서 분리하면 좋을 것 같습니다.

2020-02-18 14:38 UTC, GiPyoo commented on sprint-1/util/error.js
> +const
const 에러 날 것 같습니다 :smile:

2020-02-18 14:38 UTC, GiPyoo commented on sprint-1/util/log.js
> +  }
하나로 합치면 좋을 것 같습니다!

2020-03-17 10:12 UTC, GiPyoo approved these changes
수고 하셨습니다. 일단 스프린트2나 스프린트 3은 완성이 안되었으므로 스프린트 1을 머지하는 것으로 머지하도록 하겠습니다. 아래리뷰 확인해주세요!

2020-03-17 10:12 UTC, GiPyoo commented on sprint-1/domain/make-second.js
> +class MakeSecond {
클래스의 이름의 경우 동사로 시작하는 것 보다 행동을 하는 주체나 명사 혹은 대명사로 짓는 것이 더 가독성에 도움이 됩니다!

2020-03-17 10:12 UTC, GiPyoo commented on sprint-1/domain/make-second.js
> +  }
👍

2020-03-17 10:12 UTC, GiPyoo commented on sprint-1/util/log.js
>      console.log(this.h + "h" + this.m + "m" + this.s + "s");
h나 m이나 s 가 없는 경우에도 출력을 하는 것 같습니다. 이럴경우에는 문자열 연산을 통해 출력해도 괜찮을 것 같습니다.

2020-03-17 10:12 UTC, merged

2020-03-17 15:53 UTC, ummaeha commented on sprint-1/domain/make-second.js
> +class MakeSecond {
혹시 기표님은 저걸 어떻게 지으실것같으신가용?? -> Seconds 이런식으로 바꾸면 될까요?
메소드 이름은 동사로 시작하는 것도 상관없나요??

2020-03-18 01:12 UTC, GiPyoo commented on sprint-1/domain/make-second.js
> +class MakeSecond {
사실 이 클래스가 하는 것은 객체의 일을 한다기보다 기능의 일을 한다고 생각하기 때문에 메서드로 바꾸는게 좋지 않을까도 생각하지만 이름만 바꾼다면 Seconds 로 할 것 같습니다.
메서드는 동사로 시작하는게 좋습니다! 
👍