Kim seoyoung
JNU-econovation/web-with-js pull request #7
Opened 2020-02-25 07:03 UTC by vvvpiano

1.  array.js에서 Array.prototype.customReduce()를 정의했으나 commader.js에서 상속으로 사용하지 않고, commander의 생성자 인자로 array객체(customReduce()를 사용할 수 있도록)를 넘겨받는다는 설정으로 코드를 짰습니다.

- Array.prototype에 customReduce함수를 정의했는데, 다른 js파일에서 array.js를 require해서 사용한다 해도 customReduce함수를 찾을 수 없다고 나오고, 
`const array = require("./domain/array.js");
const arr = new array("1 2 3 4 5");
` 
와 같이 사용해야만 customReduce함수를 찾던데, prototype에 함수를 정의했는데 왜 찾지 못하는 건지 궁금합니다

- customReduce()안에는 나름 initialValue 인자가 있을 때를 고려한 조건문을 넣어봤는데, 이를 이용한 commander.js 안에는 initialValue의 존재여부를 따지는 로직이 들어있지 않습니다ㅠㅠ

2. 저번에 질문드리고 받은 피드백을 바탕으로 에러처리를 위해 callback함수를 리턴하는 방식을 적용시켜보려 했지만 일부는 성공했고 어떤 부분은 실패했습니다. 코드에 표시해놓았으니 보고 조언해주시면 감사하겠습니다!

 callback의 개념을 이해했다고 생각하면서도 막상 코드에 적용시켜 짜려니까 엄청 막막했고 더듬더듬 조잡한(??)코드를 만든것 같아서 아쉽습니다! 그래도 reduce함수를 직접 구현하면서 어느정도 조금의 감은 잡힌것 같다는 생각이 드네용! 풀리퀘 날립니당 적극적인 코드리뷰 알라뷰!!!><

2020-02-25 07:38 UTC, GiPyoo requested changes
>• Array.prototype에 customReduce함수를 정의했는데, 다른 js파일에서 array.js를 require해서 사용한다 해도 customReduce함수를 찾을 수 없다고 나오고,  
   const array = require("./domain/array.js"); const arr = new array("1 2 3 4 5");  
   와 같이 사용해야만 customReduce함수를 찾던데, prototype에 함수를 정의했는데 왜 찾지 못하는 건지 궁금합니다.

 그 이유는 prototype을 사용했을 때 표준 내장 객체의 실제 내용을 수정하지 않기 때문입니다. 때문에 이 실습은 단순히 내장 함수가 어떻게 동작하는지 이해하는 실습이었습니다. 좋은 고민입니다! 👍 

> • customReduce()안에는 나름 initialValue 인자가 있을 때를 고려한 조건문을 넣어봤는데, 이를 이용한 commander.js 안에는 initialValue의 존재여부를 따지는 로직이 들어있지 않습니다ㅠㅠ

자바스크립트에서는 순수함수라는 개념이 있습니다. 때문에 외부에서 건드릴 필요가 없다면 충분히 잘 짠 함수입니다. 그런데, 실제 reduce 함수는 initialvalue 가 존재하지 않아도 동작하는 함수입니다. 때문에 더  괜찮게 짜는 방법은 initaial 밸류라는 파라미터에 디폴트 값을 주는 것입니다. 실제 자바스크립트에서 오류가 나진 않지만 내부에서 조건문에 실제 사용 되기 때문에 값이 들어오지 않았을 때는 어떤 값으로 인식하는지 적어주면 좋을 것 같습니다.

아래 리뷰 읽어보시고 반영 부탁드립니다!

2020-02-25 07:38 UTC, GiPyoo commented on sprint-2/domain/array.js
> +  if (!initialValue && length === 0) callback(new Error("에러: reduce할 값이 없습니다."), null);
만약 initialValue가 0 혹은 false 라면 reduce할 값이 있음에도 에러가 나올 것 같습니다! 반면 null이나 undefined 같은 경우는 잘 잡아 내는 것 같습니다.

2020-02-25 07:38 UTC, GiPyoo commented on sprint-2/domain/commander.js
> +}
add 함수가 customReduce 내에서 실행 되는 것 같습니다. 이경우 콜백함수를 실행하기 위해서는 별도 실행 함수를 커링 해주어야합니다. 예
add = (callback) => (acc, cur) => {
 // 동작내용
}
이런식으로 함수를 정의해 주고 
addCallback = add(()=>{//콜백동작 내용})
이런식으로 함수를 새로 하나 만들어서 이 함수를 
result = this.input_array.customReduce(add); 이자리의 add 대신에 너어주면 callback이 싱핼 될 것 입니다.

2020-02-25 07:38 UTC, GiPyoo commented on sprint-2/domain/commander.js
> +        newset = [];
싱행 안되는 코드인 것 같습니다.

2020-02-25 07:38 UTC, GiPyoo commented on sprint-2/main.js
> +        const commander = new Commander(command, input_array);
이 부분에서 레스트 파라미터를 사용한다면 쪼개는 과정을 줄일 수 있을 것 같습니다.

2020-02-25 07:38 UTC, GiPyoo commented on sprint-2/domain/commander.js
> +  constructor(command, input_array) { // input params로 command, (custom된)array객체 들어옴
이 생성자가 레스트 파라미터를 사용하면 됩니다.

2020-02-25 07:38 UTC, GiPyoo commented on sprint-2/util/log.js
> +  static log(something, something2) {
이 함수가 하는 일이 어떤 키와 밸류를 나열하여 로깅하는 것 같습니다. 그런 역할에 맞게 파라미터이름을 고쳐주면 어떨까요?

2020-02-25 09:48 UTC, vvvpiano commented on sprint-2/domain/commander.js
> +        newset = [];
메인함수에서 콜백형태로 실행해보려고 return callback(~~~)형태로 다 수정하고 오류에 막혀서 실행이 안되긴 하는데 원래대로 return result만 하고 main에서의 테스트케이스를 돌리면 실행이 잘 되는 코드입니다!(제컴퓨터에서는요..!) 다른 부분 고치고 다시확인해보겠습니당!

2020-02-25 09:50 UTC, vvvpiano commented on sprint-2/main.js
> +        const commander = new Commander(command, input_array);
저도 처음엔 그렇게 했었는데 그렇게 되면 나머지가 기본 Array로 생성이돼서 제가 정의했던 array의 customReduce()를 사용할수 없더라구요. 레스트 파라미터를 쓰면서 customReduce()를 어떻게 쓸 수있을지 모르겠습니다!

2020-02-25 09:51 UTC, GiPyoo commented on sprint-2/domain/commander.js
> +        newset = [];
32번 라인만용.. 혹시 return 뒤에 있어도 실행이 되나용?

2020-03-04 23:36 UTC, GiPyoo requested changes
3주차 미션을 정말 잘 이해하시고 수행하신 것 같습니다. 다만 아직 2주차 리뷰가 반영이 안되 PR이 쌓이고 있습니다! 2,3 주차 리뷰 반영해주세요!

2020-03-04 23:36 UTC, GiPyoo commented on sprint-3/domain/shop.js
> +    }
recruiting++ < this.number_of_employee 이런 방식은 어떻까요

2020-03-04 23:36 UTC, GiPyoo commented on sprint-3/domain/shop.js
> +  }
좋은 생성자인 것 같습니다. :+1:

2020-03-04 23:36 UTC, GiPyoo commented on sprint-3/domain/shop.js
> +    let order_left = number_of_items;
의미상 left order 가 더 이해 되는 것 같습니다!

2020-03-04 23:36 UTC, GiPyoo commented on sprint-3/domain/shop.js
> +  }
👍 👍  굿굿 입니다

2020-03-10 19:32 UTC, vvvpiano commented
2,3주차 스프린트 리뷰반영 했습니다!

2020-03-12 05:38 UTC, GiPyoo approved these changes
굳굳 입니다. 머지할게요!

2020-03-12 05:38 UTC, GiPyoo commented on sprint-3/domain/employee.js
> +        // 더 적절하거나 conventional한 방법이 있을까요?
내부에서 this를 이용해 바꾸는 것보다 status를 받아오는 것도 있고, 이렇게 내부에서 처리하는 방법도 있습니다. 
테스트풀하게 짜기 위에서는 인풋과 아웃풋이 있는게 좋습니다. 하지만 상태의 경우에는 다른 방법으로 테스트 하는 경우도 있기 때문에 이렇게 하셔도 별 문제는 없습니다.

2020-03-12 05:38 UTC, GiPyoo commented on sprint-3/main.js
> +    const shop = new Shop(2); // 직원이 2명인 버거가게
이렇게 내부적으로 클래스를 생성하는 방법도 있겠지만 직원 클래스를 외부에서 선언해서 그 직원 배열을 주는 방법이 더 좋은 방법이라고 생각합니다!

2020-03-12 05:38 UTC, GiPyoo commented on sprint-2/main.js
> +    console.log("\ncustomReduce의 initialValue 테스트");
👍

2020-03-12 05:38 UTC, merged